import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:5000',
        changeOrigin: true,
        secure: false,
      },
    },
  },
  optimizeDeps: {
    include: [
      'axios',
      '@mui/material',
      '@mui/icons-material',
      'react-router-dom',
      '@babel/runtime/helpers/interopRequireDefault',
      '@babel/runtime/helpers/objectWithoutProperties',
      '@babel/runtime/helpers/objectSpread2',
      '@babel/runtime/helpers/typeof',
      '@babel/runtime/helpers/defineProperty',
      '@babel/runtime/helpers/extends',
      '@babel/runtime/helpers/inherits',
      '@babel/runtime/helpers/createClass',
      '@babel/runtime/helpers/classCallCheck',
      '@babel/runtime/helpers/createSuper',
      '@babel/runtime/helpers/get',
      '@babel/runtime/helpers/getPrototypeOf',
      '@babel/runtime/helpers/setPrototypeOf',
      '@babel/runtime/helpers/assertThisInitialized',
      '@babel/runtime/helpers/possibleConstructorReturn',
      '@babel/runtime/helpers/isNativeReflectConstruct',
      '@babel/runtime/helpers/construct',
      '@babel/runtime/helpers/wrapNativeSuper',
      '@babel/runtime/helpers/taggedTemplateLiteral',
      '@babel/runtime/helpers/taggedTemplateLiteralLoose',
      '@babel/runtime/helpers/asyncToGenerator',
      '@babel/runtime/helpers/awaitAsyncGenerator',
      '@babel/runtime/helpers/classPrivateFieldGet',
      '@babel/runtime/helpers/classPrivateFieldSet',
      '@babel/runtime/helpers/classPrivateFieldDestructureSet',
      '@babel/runtime/helpers/classPrivateMethodGet',
      '@babel/runtime/helpers/classPrivateMethodSet',
      '@babel/runtime/helpers/classStaticPrivateFieldSpecGet',
      '@babel/runtime/helpers/classStaticPrivateFieldSpecSet',
      '@babel/runtime/helpers/classStaticPrivateMethodGet',
      '@babel/runtime/helpers/classStaticPrivateMethodSet',
      '@babel/runtime/helpers/classExtractFieldDescriptor',
      '@babel/runtime/helpers/classApplyDescriptorGet',
      '@babel/runtime/helpers/classApplyDescriptorSet',
      '@babel/runtime/helpers/classApplyDescriptorDestructureSet',
      '@babel/runtime/helpers/classPrivateFieldInitSpec',
      '@babel/runtime/helpers/classPrivateFieldInitGet',
      '@babel/runtime/helpers/classPrivateFieldInitSet',
      '@babel/runtime/helpers/classPrivateFieldInitDestructureSet',
      '@babel/runtime/helpers/classPrivateMethodInitSpec',
      '@babel/runtime/helpers/classPrivateMethodInitGet',
      '@babel/runtime/helpers/classPrivateMethodInitSet',
      '@babel/runtime/helpers/classStaticPrivateFieldInitSpec',
      '@babel/runtime/helpers/classStaticPrivateFieldInitGet',
      '@babel/runtime/helpers/classStaticPrivateFieldInitSet',
      '@babel/runtime/helpers/classStaticPrivateMethodInitSpec',
      '@babel/runtime/helpers/classStaticPrivateMethodInitGet',
      '@babel/runtime/helpers/classStaticPrivateMethodInitSet',
      '@babel/runtime/helpers/classExtractFieldDescriptorInit',
      '@babel/runtime/helpers/classApplyDescriptorInitGet',
      '@babel/runtime/helpers/classApplyDescriptorInitSet',
      '@babel/runtime/helpers/classApplyDescriptorInitDestructureSet',
      '@babel/runtime/helpers/classPrivateFieldGet2',
      '@babel/runtime/helpers/classPrivateFieldSet2',
      '@babel/runtime/helpers/classPrivateFieldDestructureSet2',
      '@babel/runtime/helpers/classPrivateMethodGet2',
      '@babel/runtime/helpers/classPrivateMethodSet2',
      '@babel/runtime/helpers/classStaticPrivateFieldSpecGet2',
      '@babel/runtime/helpers/classStaticPrivateFieldSpecSet2',
      '@babel/runtime/helpers/classStaticPrivateMethodGet2',
      '@babel/runtime/helpers/classStaticPrivateMethodSet2',
      '@babel/runtime/helpers/classExtractFieldDescriptor2',
      '@babel/runtime/helpers/classApplyDescriptorGet2',
      '@babel/runtime/helpers/classApplyDescriptorSet2',
      '@babel/runtime/helpers/classApplyDescriptorDestructureSet2',
      '@babel/runtime/helpers/classPrivateFieldInitSpec2',
      '@babel/runtime/helpers/classPrivateFieldInitGet2',
      '@babel/runtime/helpers/classPrivateFieldInitSet2',
      '@babel/runtime/helpers/classPrivateFieldInitDestructureSet2',
      '@babel/runtime/helpers/classPrivateMethodInitSpec2',
      '@babel/runtime/helpers/classPrivateMethodInitGet2',
      '@babel/runtime/helpers/classPrivateMethodInitSet2',
      '@babel/runtime/helpers/classStaticPrivateFieldInitSpec2',
      '@babel/runtime/helpers/classStaticPrivateFieldInitGet2',
      '@babel/runtime/helpers/classStaticPrivateFieldInitSet2',
      '@babel/runtime/helpers/classStaticPrivateMethodInitSpec2',
      '@babel/runtime/helpers/classStaticPrivateMethodInitGet2',
      '@babel/runtime/helpers/classStaticPrivateMethodInitSet2',
      '@babel/runtime/helpers/classExtractFieldDescriptorInit2',
      '@babel/runtime/helpers/classApplyDescriptorInitGet2',
      '@babel/runtime/helpers/classApplyDescriptorInitSet2',
      '@babel/runtime/helpers/classApplyDescriptorInitDestructureSet2',
    ],
  },
  build: {
    commonjsOptions: {
      include: [/node_modules/],
      transformMixedEsModules: true,
    },
  },
  resolve: {
    alias: {
      '@babel/runtime': '@babel/runtime/helpers',
    },
  },
})
